[2024-02-25T14:12:05.643+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: demo.hello manual__2024-02-25T14:11:08.108809+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
