[2024-02-25T15:12:02.927+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: demo.hello scheduled__2024-02-20T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
